target-version = "py311"
line-length = 100

[lint]
select = ["E9", "F", "I"]

[lint.isort]
known-first-party = ["src"]
split-on-trailing-comma = false

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = false
line-ending = "lf"
