target-version = "py311"
line-length = 100

[lint]
select = ["E9", "F63", "F7", "F82"]

[lint.isort]
known-first-party = ["src"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = false
line-ending = "lf"
