import os
import re
import json

prefix_translations = {
    "/notifications": "/thong-bao",
    "/ingest": "/nap-du-lieu",
    "/chat": "/tro-chuyen",
    "/inference": "/suy-luan",
    "/finetune": "/tinh-chinh",
    "/collectors": "/thu-thap",
    "/users": "/nguoi-dung",
    "/audit": "/kiem-toan",
    "/profile": "/ho-so",
    "/quota": "/han-muc",
    "/telemetry": "/giam-sat",
    "/operations": "/van-hanh",
    "/banners": "/quang-cao",
    "/pin": "/ghim",
    "/versions": "/phien-ban",
    "/library": "/thu-vien",
    "/upload": "/tai-len",
    "/discovery": "/kham-pha",
    "/reading": "/doc-hieu",
    "/export": "/ket-xuat",
    "/reviews": "/danh-gia",
    "/bookmarks": "/danh-dau",
    "/collaboration": "/cong-tac",
    "/documents": "/tai-lieu",
    "/publications": "/xuat-ban",
    "/storage": "/luu-tru",
    "/highlights": "/danh-dau-dong",
    "/drafts": "/ban-nhap",
    "/editor": "/trinh-soan-thao",
    "/messages": "/tin-nhan",
    "/withdrawals": "/rut-tien",
    "/deposits": "/nap-tien",
    "/coupons": "/ma-giam-gia",
    "/monetization": "/kiem-tien",
    "/wallets": "/vi-tien",
    "/auth": "/xac-thuc",
    "/passkeys": "/khoa-xac-thuc",
    "/editorjs": "/soan-thao-editorjs",
    "/latex": "/soan-thao-latex",
}

path_translations = {
    # Notifications
    "/mark-read": "/danh-dau-da-doc",
    "/{notif_id}/read": "/{notif_id}/doc-hieu",
    "/unread-count": "/so-luong-chua-doc",
    "/{notif_id}/dismiss": "/{notif_id}/bo-qua",
    "/clear-all": "/xoa-tat-ca",
    "/mark-all-read": "/danh-dau-da-doc-tat-ca",
    "/preferences": "/tuy-chon",
    "/subscribe": "/dang-ky",
    "/batch": "/hang-loat",
    "/trigger": "/kich-hoat",
    "/dispatch": "/gui-di",
    # Auth & Users
    "/me": "/ca-nhan",
    "/forgot-password": "/quen-mat-khau",
    "/reset-password": "/dat-lai-mat-khau",
    "/verify-code": "/xac-nhan-ma",
    "/login/start": "/dang-nhap/bat-dau",
    "/login/finish": "/dang-nhap/hoan-tat",
    "/google/login": "/google/dang-nhap",
    "/google/callback": "/google/phan-hoi",
    "/search": "/tim-kiem",
    "/role": "/vai-tro",
    "/status": "/trang-thai",
    "/warn": "/canh-bao",
    "/lock": "/khoa",
    "/shadowban": "/cam-ngam",
    "/kyc": "/xac-minh-danh-tinh",
    "/notes": "/ghi-chu",
    "/reports": "/bao-cao",
    "/reports/{report_id}": "/bao-cao/{report_id}",
    "/activity-log": "/nhat-ky-hoat-dong",
    "/logs": "/nhat-ky-hoat-dong",  # ensuring consistency
    "/by-email/{email}": "/theo-email/{email}",
    "/by-slug/{slug}": "/theo-ten-mien/{slug}",
    # Documents / Content
    "/trash": "/thung-rac",
    "/personal": "/ca-nhan",
    "/recent": "/gan-day",
    "/stats": "/thong-ke",
    "/{document_id}/restore": "/{document_id}/khoi-phuc",
    "/{document_id}/content": "/{document_id}/noi-dung",
    "/{document_id}/publish": "/{document_id}/xuat-ban",
    "/{document_id}/unpublish": "/{document_id}/huy-xuat-ban",
    "/{document_id}/password": "/{document_id}/mat-khau",
    "/{document_id}/transfer": "/{document_id}/chuyen-nhuong",
    "/{document_id}/tags": "/{document_id}/the",
    "/{document_id}/academic-index": "/{document_id}/chi-so-hoc-thuat",
    "/{document_id}/readability": "/{document_id}/do-de-doc",
    "/{document_id}/sync": "/{document_id}/dong-bo",
    "/{document_id}/plagiarism-check": "/{document_id}/kiem-tra-dao-van",
    "/{document_id}/check-grammar": "/{document_id}/kiem-tra-ngu-phap",
    "/{document_id}/check-logic": "/{document_id}/kiem-tra-logic",
    "/{document_id}/summarize": "/{document_id}/tom-tat",
    "/{document_id}/extract-tags": "/{document_id}/trich-xuat-the",
    "/{document_id}/compare-versions": "/{document_id}/so-sanh-phien-ban",
    "/{document_id}/ai-suggestions": "/{document_id}/goi-y-ai",
    "/{document_id}/comments": "/{document_id}/binh-luan",
    "/{document_id}/find-replace": "/{document_id}/tim-va-thay-the",
    "/{document_id}/auto-save": "/{document_id}/tu-dong-luu",
    # File Operations
    "/folders": "/thu-muc",
    "/files": "/tap-tin",
    "/files/{item_id}": "/tap-tin/{item_id}",
    "/files/{item_id}/share": "/tap-tin/{item_id}/chia-se",
    "/shares/{share_token}": "/chia-se/{share_token}",
    "/lists": "/danh-sach",
    "/download-archive": "/tai-ve-luu-tru",
    # Financial
    "/purchase/document": "/mua/tai-lieu",
    "/membership": "/thanh-vien",
    "/pricing": "/bang-gia",
    "/balance": "/so-du",
    "/transactions": "/giao-dich",
    "/revenue": "/doanh-thu",
    "/queue": "/hang-doi",
    "/{withdrawal_id}/verify": "/{withdrawal_id}/xac-minh",
    "/{withdrawal_id}/process": "/{withdrawal_id}/xu-ly",
    "/redeem": "/su-dung",
    # Collab & Messages
    "/conversations": "/cuoc-tro-chuyen",
    "/{message_id}/pin": "/{message_id}/ghim",
    "/{message_id}/reactions": "/{message_id}/bay-to-cam-xuc",
    "/{message_id}/translate": "/{message_id}/dich-thuat",
    "/{other_user_id}/read": "/{other_user_id}/doc-hieu",
    "/{other_user_id}/block": "/{other_user_id}/chan",
    "/{other_user_id}/unblock": "/{other_user_id}/bo-chan",
    "/{other_user_id}/block-status": "/{other_user_id}/trang-thai-chan",
    "/conversations/{other_user_id}/pin": "/cuoc-tro-chuyen/{other_user_id}/ghim",
    "/{other_user_id}/drafts": "/{other_user_id}/ban-nhap",
    "/{other_user_id}/self-destruct": "/{other_user_id}/tu-huy",
    "/{other_user_id}/mute": "/{other_user_id}/tat-thong-bao",
    "/{other_user_id}/settings": "/{other_user_id}/cai-dat",
    "/{receiver_id}/documents/share": "/{receiver_id}/tai-lieu/chia-se",
    "/{other_user_id}/documents/shared": "/{other_user_id}/tai-lieu/da-chia-se",
    "/groups": "/nhom",
    # Operations
    "/active-jobs": "/cong-viec-dang-chay",
    "/active-processes": "/tien-trinh-dang-chay",
    "/stop": "/dung",
    # Editor & Utils
    "/compile": "/bien-dich",
    "/format": "/dinh-dang",
    "/export/{format}": "/ket-xuat/{format}",
    "/export-zip": "/ket-xuat-zip",
    "/pomodoro": "/dong-ho-pomodoro",
    # Agentic AI
    "/upload": "/tai-len",
    "/chunk": "/phan-chia",
    "/embed": "/nhung",
    "/index": "/danh-muc",
    "/{doc_id}/stream": "/{doc_id}/phat-truc-tiep",
    "/translate": "/dich-thuat",
    "/summarize": "/tom-tat",
    "/grammar": "/ngu-phap",
    "/extract": "/trich-xuat",
    "/detect": "/nhan-dien",
    "/moderate": "/kiem-duyet",
    "/jobs": "/cong-viec",
    "/{job_id}/status": "/{job_id}/trang-thai",
    "/{job_id}/cancel": "/{job_id}/huy-bo",
    "/{job_id}/metrics": "/{job_id}/chi-so",
    # Collector
    "/trigger": "/kich-hoat",
    "/{collector_id}/logs": "/{collector_id}/nhat-ky-hoat-dong",
}

with open("translation_dict.json", "w") as f:
    json.dump(
        {"prefixes": prefix_translations, "paths": path_translations}, f, indent=4
    )
