FUNCTION_IDS = {
    "register_user": ["AUTH-01"],
    "resend_email_verification": ["AUTH-02"],
    "verify_email": ["AUTH-02"],
    "login": ["AUTH-03"],
    "forgot_password": ["AUTH-08"],
    "reset_password": ["AUTH-09"],
    "verify_code": ["AUTH-09"],
    "logout": ["AUTH-07"],
    "logout_all": ["AUTH-07", "ACC-07"],
    "refresh_session": ["AUTH-06"],
    "google_login": ["AUTH-04"],
    "google_callback": ["AUTH-04"],
    "passkey_login_begin": ["AUTH-05"],
    "passkey_login_finish": ["AUTH-05"],
    "passkey_register_begin": ["ACC-08"],
    "passkey_register_finish": ["ACC-08"],
    "read_users_me": ["ACC-01"],
    "update_users_me": ["ACC-02"],
    "change_email": ["ACC-03"],
    "change_password": ["ACC-04"],
    "list_my_sessions": ["ACC-05"],
    "revoke_my_session": ["ACC-06"],
    "read_settings": ["ACC-09"],
    "update_settings": ["ACC-09"],
    "update_notifications": ["ACC-10"],
    "deactivate_account": ["ACC-13"],
    "create_account": ["ADM-USR-03", "ADM-USR-04"],
    "list_accounts": ["ADM-USR-01"],
    "update_account": ["ADM-USR-05"],
    "account_detail": ["ADM-USR-02"],
    "update_account_profile": ["ADM-USR-05"],
    "enable_account": ["ADM-USR-06"],
    "disable_account": ["ADM-USR-07"],
    "lock_account": ["ADM-USR-08"],
    "unlock_account": ["ADM-USR-09"],
    "force_password_reset": ["ADM-USR-11"],
    "list_user_sessions": ["ADM-USR-12"],
    "revoke_user_session": ["ADM-USR-13"],
    "revoke_all_user_sessions": ["ADM-USR-13"],
    "reset_user_passkeys": ["ADM-USR-14"],
    "update_system_role": ["ADM-USR-15", "ADM-USR-16"],
    "list_user_memberships": ["ADM-USR-17"],
    "list_user_audit": ["ADM-USR-18"],
    "resend_account_activation": ["ADM-USR-10"],
    "anonymize_user": ["ADM-USR-19"],
    "preview_bulk_user_action": ["ADM-USR-20"],
    "confirm_bulk_user_action": ["ADM-USR-20"],
    "list_project_metadata": ["ADM-PRJ-01"],
    "project_metadata_detail": ["ADM-PRJ-02"],
    "get_project_policy": ["ADM-PRJ-03"],
    "update_project_policy": ["ADM-PRJ-03"],
    "update_project_status": ["ADM-PRJ-04"],
    "update_project_quota": ["ADM-PRJ-05"],
    "project_membership_diagnostics": ["ADM-PRJ-06"],
    "hard_delete_project": ["ADM-PRJ-07"],
    "list_break_glass_grants": ["ADM-PRJ-08"],
    "create_break_glass_grant": ["ADM-PRJ-08"],
    "revoke_break_glass_grant": ["ADM-PRJ-08"],
    "get_auth_policy": ["ADM-SEC-01", "ADM-SEC-02", "ADM-SEC-03", "ADM-SEC-04", "ADM-SEC-05"],
    "update_auth_policy": ["ADM-SEC-01", "ADM-SEC-02", "ADM-SEC-03", "ADM-SEC-04", "ADM-SEC-05"],
    "get_rate_limits": ["ADM-SEC-06"],
    "update_rate_limits": ["ADM-SEC-06"],
    "list_service_identities": ["ADM-SEC-07"],
    "create_service_identity": ["ADM-SEC-07"],
    "rotate_service_identity": ["ADM-SEC-07"],
    "security_audit": ["ADM-SEC-08"],
    "emergency_revoke": ["ADM-SEC-10"],
    "list_ai_providers": ["ADM-AI-01"],
    "update_ai_provider": ["ADM-AI-02"],
    "list_ai_models": ["ADM-AI-03"],
    "register_ai_model": ["ADM-AI-03"],
    "update_ai_model": ["ADM-AI-03"],
    "get_ai_defaults": ["ADM-AI-04", "ADM-AI-05", "ADM-AI-06"],
    "update_ai_defaults": ["ADM-AI-04", "ADM-AI-05", "ADM-AI-06"],
    "test_ai_provider": ["ADM-AI-09"],
    "get_ai_versions": ["ADM-AI-10"],
    "get_integrations": ["ADM-INT-01", "ADM-INT-05", "ADM-INT-06", "ADM-INT-08", "ADM-INT-09", "ADM-INT-10"],
    "update_integrations": ["ADM-INT-01", "ADM-INT-05", "ADM-INT-06"],
    "test_smtp": ["ADM-INT-02"],
    "get_storage_config": ["ADM-INT-03"],
    "update_storage_config": ["ADM-INT-03"],
    "test_storage": ["ADM-INT-04"],
    "integration_health": ["ADM-INT-08", "ADM-INT-09", "ADM-INT-10"],
    "list_secret_references": ["ADM-INT-07"],
    "create_secret_reference": ["ADM-INT-07"],
    "rotate_secret_reference": ["ADM-INT-07"],
    "delete_secret_reference": ["ADM-INT-07"],
    "platform_health": ["ADM-OPS-01"],
    "queue_overview": ["ADM-OPS-02"],
    "list_operations_jobs": ["ADM-OPS-03"],
    "retry_operations_job": ["ADM-OPS-04"],
    "cancel_operations_job": ["ADM-OPS-05"],
    "list_dead_letter_jobs": ["ADM-OPS-06"],
    "discard_dead_letter_job": ["ADM-OPS-06"],
    "requeue_dead_letter_job": ["ADM-OPS-06"],
    "rag_operations": ["ADM-OPS-07"],
    "request_rag_reindex": ["ADM-OPS-07"],
    "inspect_safe_caches": ["ADM-OPS-08"],
    "clear_safe_caches": ["ADM-OPS-08"],
    "storage_usage": ["ADM-OPS-09"],
    "operations_metrics": ["ADM-OPS-10"],
    "get_maintenance_mode": ["ADM-OPS-11"],
    "update_maintenance_mode": ["ADM-OPS-11"],
    "runtime_versions": ["ADM-OPS-12"],
    "list_auth_audit": ["ADM-CFG-01"],
    "export_global_audit": ["ADM-CFG-02"],
    "get_system_config": ["ADM-CFG-03", "ADM-CFG-04", "ADM-CFG-05", "ADM-CFG-06", "ADM-CFG-07", "ADM-CFG-08"],
    "update_system_config": ["ADM-CFG-03", "ADM-CFG-04", "ADM-CFG-05", "ADM-CFG-06", "ADM-CFG-07", "ADM-CFG-08"],
}


ROUTE_NAME_FUNCTION_IDS = {
    "get_feature_flags": ["ADM-CFG-03"],
    "update_feature_flags": ["ADM-CFG-03"],
    "get_localization": ["ADM-CFG-04"],
    "update_localization": ["ADM-CFG-04"],
    "get_retention": ["ADM-CFG-05"],
    "update_retention": ["ADM-CFG-05"],
    "get_default_quotas": ["ADM-CFG-06"],
    "update_default_quotas": ["ADM-CFG-06"],
    "get_import_export": ["ADM-CFG-07", "ADM-CFG-08"],
    "update_import_export": ["ADM-CFG-07", "ADM-CFG-08"],
    "get_break_glass_policy": ["ADM-SEC-09"],
    "update_break_glass_policy": ["ADM-SEC-09"],
    "get_ai_limits": ["ADM-AI-07"],
    "update_ai_limits": ["ADM-AI-07"],
    "get_ai_retrieval": ["ADM-AI-08"],
    "update_ai_retrieval": ["ADM-AI-08"],
}


def apply_function_ids(app):
    for route in app.routes:
        endpoint = getattr(route, "endpoint", None)
        function_ids = FUNCTION_IDS.get(getattr(endpoint, "__name__", ""))
        if not function_ids:
            function_ids = ROUTE_NAME_FUNCTION_IDS.get(getattr(route, "name", ""))
        if not function_ids:
            continue
        route.openapi_extra = {
            **(getattr(route, "openapi_extra", None) or {}),
            "x-function-ids": function_ids,
        }
