from src.tools.document import (
    update_document_metadata,
    get_my_documents,
    get_trash_documents,
    delete_document,
    restore_document,
    get_document_analytics,
    read_document,
    recommend_documents,
)
from src.tools.mindmap import generate_mindmap
from src.tools.instructions import manage_user_instructions
from src.workflow.reduction import agent_summarize_long_document
from src.tools.qa import (
    apply_test_case_revision,
    approve_test_case_version,
    baseline_requirement_version,
    compare_requirement_versions,
    confirm_trace_link,
    create_impact_analysis,
    create_maintenance_proposal,
    create_regression_recommendation,
    create_test_case_draft,
    create_trace_link_suggestion,
    find_near_duplicates,
    get_acceptance_criteria,
    get_historical_defects,
    get_project_context,
    get_requirement_version,
    get_test_case_version,
    get_test_results,
    get_trace_links,
    mark_test_case_obsolete,
    search_project_knowledge,
    search_test_cases,
)

tools = [
    agent_summarize_long_document,
    update_document_metadata,
    get_my_documents,
    read_document,
    recommend_documents,
    generate_mindmap,
    manage_user_instructions,
    get_trash_documents,
    delete_document,
    restore_document,
    get_document_analytics,
    get_project_context,
    search_project_knowledge,
    get_requirement_version,
    compare_requirement_versions,
    get_acceptance_criteria,
    get_trace_links,
    search_test_cases,
    get_test_case_version,
    get_test_results,
    get_historical_defects,
    find_near_duplicates,
    create_test_case_draft,
    create_trace_link_suggestion,
    create_impact_analysis,
    create_maintenance_proposal,
    create_regression_recommendation,
    apply_test_case_revision,
    confirm_trace_link,
    baseline_requirement_version,
    approve_test_case_version,
    mark_test_case_obsolete,
]
