from src.tools.document import (
    update_document_metadata,
    get_my_documents,
    get_trash_documents,
    delete_document,
    restore_document,
    get_document_analytics,
    read_document,
    recommend_documents,
)
from src.tools.mindmap import generate_mindmap
from src.tools.instructions import manage_user_instructions
from src.workflow.reduction import agent_summarize_long_document
from src.tools.assessment import (
    analyze_question,
    analyze_blueprint_impact,
    compare_difficulty_signals,
    create_question_draft,
    create_revision_draft,
    evaluate_learner_fit,
    get_curriculum_context,
    get_teacher_material_context,
    get_item_calibration,
    get_question_research_metrics,
    get_research_evaluation,
    import_assessment,
    inspect_question_versions,
    map_question_to_curriculum,
    predict_item_difficulty,
    propose_question_revision,
    publish_assessment_version,
    record_teacher_difficulty_estimate,
    run_calibration,
    verify_construct_preservation,
)

tools = [
    agent_summarize_long_document,
    update_document_metadata,
    get_my_documents,
    read_document,
    recommend_documents,
    generate_mindmap,
    manage_user_instructions,
    get_trash_documents,
    delete_document,
    restore_document,
    get_document_analytics,
    get_curriculum_context,
    get_teacher_material_context,
    map_question_to_curriculum,
    create_question_draft,
    import_assessment,
    analyze_question,
    record_teacher_difficulty_estimate,
    predict_item_difficulty,
    get_item_calibration,
    compare_difficulty_signals,
    inspect_question_versions,
    get_question_research_metrics,
    get_research_evaluation,
    evaluate_learner_fit,
    analyze_blueprint_impact,
    run_calibration,
    verify_construct_preservation,
    propose_question_revision,
    create_revision_draft,
    publish_assessment_version,
]
