FUNCTION_IDS = {
    "create_project": ["PRJ-02", "ACC-12"],
    "list_projects": ["PRJ-01", "ACC-11"],
    "project_detail": ["PRJ-03"],
    "update_project": ["PRJ-04"],
    "archive_project": ["PRJ-05"],
    "restore_project": ["PRJ-06"],
    "list_project_members": ["MEM-01"],
    "add_project_member": ["MEM-02"],
    "invite_project_member": ["MEM-02"],
    "accept_project_invitation": ["MEM-SELF-01"],
    "accept_project_invitation_by_id": ["MEM-SELF-01"],
    "decline_project_invitation": ["MEM-SELF-02"],
    "leave_project": ["MEM-SELF-03"],
    "resend_project_invitation": ["MEM-03"],
    "cancel_project_invitation": ["MEM-04"],
    "update_project_member": ["MEM-05", "MEM-06", "MEM-07"],
    "remove_project_member": ["MEM-08"],
    "create_requirement": ["REQ-03"],
    "list_requirements": ["REQ-01"],
    "requirement_detail": ["REQ-02"],
    "update_requirement_draft": ["REQ-04", "REQ-05", "REQ-06"],
    "add_requirement_dependency": ["REQ-07"],
    "remove_requirement_dependency": ["REQ-07"],
    "create_requirement_version": ["REQ-15"],
    "list_requirement_versions": ["REQ-16"],
    "submit_requirement_review": ["REQ-11"],
    "submit_requirement_review_alias": ["REQ-11"],
    "request_requirement_changes": ["REQ-12", "REQ-13"],
    "baseline_requirement_version": ["REQ-14"],
    "approve_requirement": ["REQ-14"],
    "approve_requirement_alias": ["REQ-14"],
    "mark_requirement_obsolete": ["REQ-18"],
    "restore_requirement": ["REQ-19"],
    "lint_requirement": ["REQ-10", "AI-02"],
    "lint_requirement_draft": ["REQ-10", "AI-02"],
    "lint_requirement_alias": ["REQ-10", "AI-02"],
    "compare_requirement": ["REQ-17"],
    "diff_requirement": ["REQ-17"],
    "split_requirement": ["REQ-20"],
    "merge_requirements": ["REQ-21"],
    "find_duplicate_requirements": ["REQ-22"],
    "create_requirement_document": ["RDOC-04"],
    "upload_requirement_document": ["RDOC-05"],
    "list_requirement_documents": ["RDOC-01"],
    "create_knowledge_source": ["RDOC-01", "KN-03"],
    "list_knowledge_sources": ["RDOC-01", "KN-02"],
    "archive_knowledge_source": ["RDOC-12", "KN-06"],
    "get_requirement_document": ["RDOC-02"],
    "update_requirement_document_metadata": ["RDOC-08", "KN-04"],
    "reindex_requirement_document": ["RDOC-14", "KN-05"],
    "download_requirement_document": ["RDOC-03"],
    "archive_requirement_document": ["RDOC-12"],
    "restore_requirement_document": ["RDOC-13"],
    "retry_requirement_document_parse": ["RDOC-06"],
    "extract_requirement_document": ["RDOC-06"],
    "create_requirement_import": ["RDOC-04"],
    "upload_requirement_import": ["RDOC-05"],
    "get_requirement_import": ["RDOC-07"],
    "review_requirement_import": ["RDOC-08"],
    "merge_requirement_candidates": ["RDOC-09"],
    "split_requirement_candidate": ["RDOC-09"],
    "reject_requirement_candidate": ["RDOC-10"],
    "confirm_requirement_import": ["RDOC-11"],
    "create_review_comment": ["COM-02", "REQ-09", "TC-08"],
    "list_review_comments": ["COM-01"],
    "update_review_comment": ["COM-03"],
    "delete_review_comment": ["COM-04"],
    "resolve_review_comment": ["COM-05"],
    "reopen_review_comment": ["COM-05"],
    "create_scenario": ["TSC-03"],
    "list_scenarios": ["TSC-01"],
    "get_test_scenario": ["TSC-02"],
    "update_scenario": ["TSC-05"],
    "clone_scenario": ["TSC-06"],
    "archive_scenario": ["TSC-07"],
    "generate_scenarios": ["TSC-04", "AI-03"],
    "create_test_case_draft": ["TC-03"],
    "list_test_case_drafts": ["TC-01"],
    "get_test_case_draft": ["TC-02"],
    "get_test_case": ["TC-02"],
    "update_test_case_draft": ["TC-04", "TC-05", "TC-06"],
    "lint_test_case_draft": ["TC-13"],
    "submit_test_case_review": ["TC-16"],
    "submit_test_case_review_alias": ["TC-16"],
    "request_test_case_changes": ["TC-17", "TC-18"],
    "freeze_test_case_draft": ["TC-19"],
    "approve_test_case": ["TC-19"],
    "approve_test_case_alias": ["TC-19"],
    "list_test_cases": ["TC-01"],
    "clone_test_case": ["TC-09"],
    "list_test_case_versions": ["TC-21"],
    "create_test_case_version_draft": ["TC-20"],
    "diff_test_case_versions": ["TC-22"],
    "mark_test_case_obsolete": ["TC-23"],
    "restore_test_case": ["TC-24"],
    "generate_test_cases": ["TC-15", "AI-04"],
    "generate_project_test_cases": ["TC-15"],
    "find_duplicates": ["TC-14", "AI-05"],
    "list_templates": ["TPLT-01"],
    "get_template": ["TPLT-01"],
    "create_template": ["TPLT-02"],
    "update_template": ["TPLT-02"],
    "archive_template": ["TPLT-03"],
    "list_device_matrices": ["DEVMTX-01"],
    "get_device_matrix": ["DEVMTX-01"],
    "create_device_matrix": ["DEVMTX-02"],
    "update_device_matrix": ["DEVMTX-02"],
    "archive_device_matrix": ["DEVMTX-02"],
    "assign_device_matrix": ["DEVMTX-03"],
    "list_notification_watches": ["NTF-04"],
    "set_notification_watch": ["NTF-04"],
    "get_project_notification_rules": ["NTF-05"],
    "update_project_notification_rules": ["NTF-05"],
    "get_project_notification_preferences": ["NTF-06"],
    "update_project_notification_preferences": ["NTF-06"],
    "list_security_test_suggestions": ["SEC-TST-01"],
    "generate_security_test_suggestions": ["SEC-TST-01"],
    "list_performance_plan_drafts": ["PERF-01"],
    "generate_performance_plan_draft": ["PERF-01"],
    "list_webhook_subscriptions": ["WH-01"],
    "create_webhook_subscription": ["WH-01"],
    "update_webhook_subscription": ["WH-01"],
    "list_webhook_deliveries": ["WH-02"],
    "replay_webhook_delivery": ["WH-03"],
    "list_automation_script_drafts": ["SCR-01"],
    "get_automation_script_draft": ["SCR-01"],
    "generate_automation_script_draft": ["SCR-01"],
    "update_automation_script_draft": ["SCR-02"],
    "export_automation_script_draft": ["SCR-03"],
    "approve_automation_script_draft": ["SCR-04"],
    "list_project_connectors": ["CONN-01"],
    "bind_project_connector": ["CONN-02"],
    "update_project_connector": ["CONN-03"],
    "unbind_project_connector": ["CONN-02"],
    "start_connector_sync": ["CONN-04"],
    "list_connector_conflicts": ["CONN-05"],
    "resolve_connector_conflict": ["CONN-05"],
    "list_connector_sync_log": ["CONN-06"],
    "list_automation_executions": ["AUTO-01"],
    "get_automation_execution": ["AUTO-01"],
    "create_automation_execution": ["AUTO-02"],
    "start_automation_execution": ["AUTO-03"],
    "cancel_automation_execution": ["AUTO-03"],
    "get_automation_evidence": ["AUTO-04"],
    "ingest_automation_result": ["AUTO-05"],
    "list_cicd_state": ["CI-05"],
    "create_cicd_binding": ["CI-01"],
    "update_cicd_binding": ["CI-01"],
    "trigger_cicd_run": ["CI-02"],
    "ingest_cicd_result": ["CI-03"],
    "retry_cicd_run": ["CI-04"],
    "update_collaboration_presence": ["COL-01"],
    "list_collaboration_presence": ["COL-01"],
    "apply_requirement_collaboration_operation": ["COL-02"],
    "apply_test_case_collaboration_operation": ["COL-03"],
    "list_collaboration_conflicts": ["COL-04"],
    "resolve_collaboration_conflict": ["COL-04"],
    "create_trace_link": ["TRC-02", "TRC-03"],
    "confirm_trace_link": ["TRC-04"],
    "reject_trace_link": ["TRC-05"],
    "revoke_trace_link": ["TRC-06"],
    "traceability": ["TRC-01"],
    "coverage": ["TRC-08", "COV-01", "COV-02"],
    "requirement_coverage": ["TRC-01"],
    "list_coverage_snapshots": ["RPT-09"],
    "create_coverage_snapshot": ["RPT-09", "COV-03"],
    "test_case_trace": ["TRC-01"],
    "export_traceability": ["RPT-08", "COV-04"],
    "recover_trace_links": ["TRC-07"],
    "create_change_set": ["CHG-02"],
    "list_change_sets": ["CHG-01"],
    "get_change_set": ["CHG-03"],
    "review_change_set": ["CHG-04"],
    "analyze_impact": ["IMP-02", "AI-06"],
    "get_change_set_impact_analysis": ["IMP-01"],
    "get_impact_analysis": ["IMP-01"],
    "review_impact_analysis": ["IMP-03", "IMP-04", "IMP-06"],
    "rerun_impact_analysis": ["IMP-05"],
    "add_impact_review_perspective": ["IMP-03"],
    "create_maintenance_proposals": ["PROP-01", "AI-07"],
    "list_proposals": ["PROP-01"],
    "get_maintenance_proposal": ["PROP-02"],
    "review_project_proposal": ["PROP-03", "PROP-04"],
    "accept_proposal": ["PROP-07"],
    "approve_project_proposal": ["PROP-06"],
    "accept_proposal_with_edit": ["PROP-04", "PROP-07"],
    "reject_proposal": ["PROP-05"],
    "reject_project_proposal": ["PROP-05"],
    "regenerate_proposal": ["PROP-08"],
    "regression_recommendation": ["REG-02", "AI-08"],
    "get_change_set_regression_recommendation": ["REG-01"],
    "generate_project_regression": ["REG-02"],
    "get_regression_recommendation": ["REG-01"],
    "edit_regression_recommendation": ["REG-03"],
    "approve_regression_recommendation": ["REG-04"],
    "approve_project_regression": ["REG-04"],
    "create_test_plan": ["TPL-03"],
    "list_test_plans": ["TPL-01"],
    "get_test_plan": ["TPL-02"],
    "update_test_plan": ["TPL-04", "TPL-05", "TPL-06"],
    "submit_test_plan": ["TPL-07"],
    "approve_test_plan": ["TPL-08"],
    "archive_test_plan": ["TPL-10"],
    "clone_test_plan": ["TPL-09"],
    "create_test_suite": ["TSU-03"],
    "list_test_suites": ["TSU-01"],
    "get_test_suite": ["TSU-02"],
    "update_test_suite": ["TSU-04"],
    "clone_test_suite": ["TSU-05"],
    "archive_test_suite": ["TSU-06"],
    "create_test_run": ["RUN-03", "REG-05"],
    "list_test_runs": ["RUN-01"],
    "get_test_run": ["RUN-02"],
    "update_test_run": ["RUN-04"],
    "assign_test_run": ["RUN-05"],
    "start_test_run": ["RUN-06"],
    "resume_test_run": ["RUN-15"],
    "record_test_result": ["RUN-07", "RUN-08", "RUN-09", "RUN-16"],
    "list_test_results": ["RUN-07"],
    "patch_test_execution": ["RUN-08", "RUN-16"],
    "correct_test_result": ["RUN-10"],
    "complete_test_run": ["RUN-12"],
    "abort_test_run": ["RUN-13"],
    "export_test_run_report": ["RUN-14"],
    "create_defect": ["RUN-11", "DEF-03"],
    "list_defects": ["DEF-01"],
    "defect_detail": ["DEF-02"],
    "find_duplicate_defects": ["DEF-17", "DEF-20"],
    "suggest_defect_trace": ["AI-10"],
    "find_defect_trace_candidates": ["AI-10"],
    "update_defect_trace": ["DEF-07"],
    "update_defect": ["DEF-04", "DEF-05", "DEF-06", "DEF-08"],
    "transition_defect": ["DEF-09", "DEF-10", "DEF-11", "DEF-12", "DEF-16", "DEF-18"],
    "retest_defect": ["DEF-13", "DEF-14", "DEF-15"],
    "export_defects": ["DEF-19"],
    "search_knowledge": ["AI-01", "KN-01"],
    "ask_project": ["AI-01"],
    "maintenance_analytics": ["RPT-05"],
    "ai_analytics": ["RPT-06", "AI-09"],
    "execution_report": ["RPT-03"],
    "defect_report": ["RPT-04"],
    "dashboard": ["RPT-01", "RPT-02"],
    "register_attachment": ["ATT-02", "REQ-08", "TC-07"],
    "list_attachments": ["ATT-01"],
    "delete_attachment": ["ATT-03"],
    "moderate_attachment": ["ATT-04"],
    "import_api_artifact": ["API-02", "API-03"],
    "list_api_operations": ["API-01"],
    "generate_api_tests": ["API-06"],
    "preview_test_import": ["TC-10"],
    "upload_test_import": ["TC-10"],
    "confirm_test_import": ["TC-11"],
    "export_test_cases": ["TC-12"],
    "bulk_tags": ["BULK-01"],
    "bulk_add_to_suite": ["BULK-02"],
    "bulk_mark_review_required": ["BULK-03"],
    "bulk_generate_proposals": ["BULK-04"],
    "bulk_approve_proposals": ["BULK-05"],
    "bulk_archive": ["BULK-06"],
    "list_releases": ["REL-01"],
    "get_release": ["REL-02"],
    "create_release": ["REL-03"],
    "update_release": ["REL-04"],
    "activate_release": ["REL-05"],
    "close_release": ["REL-06"],
    "archive_release": ["REL-07"],
    "list_builds": ["BLD-01"],
    "get_build": ["BLD-01"],
    "create_build": ["BLD-02"],
    "update_build": ["BLD-02"],
    "set_current_build": ["BLD-03"],
    "list_environments": ["ENV-01"],
    "get_environment": ["ENV-01"],
    "create_environment": ["ENV-02"],
    "update_environment": ["ENV-03"],
    "update_environment_secrets": ["ENV-04"],
    "archive_environment": ["ENV-05"],
    "create_data_set": ["DATA-02"],
    "list_data_sets": ["DATA-01"],
    "get_data_set": ["DATA-01"],
    "list_data_set_versions": ["DATA-01"],
    "create_data_set_version": ["DATA-03"],
    "bind_data_set": ["DATA-04"],
    "preview_data_set": ["DATA-05"],
    "archive_data_set": ["DATA-06"],
    "get_risk_ranking": ["RISK-01"],
    "generate_risk_ranking": ["RISK-02"],
    "review_risk_ranking": ["RISK-03"],
    "approve_risk_ranking": ["RISK-04"],
    "list_templates": ["TPLT-01"],
    "get_template": ["TPLT-01"],
    "create_template": ["TPLT-02"],
    "update_template": ["TPLT-02"],
    "archive_template": ["TPLT-03"],
    "review_api_artifact": ["API-04"],
    "confirm_api_artifact": ["API-05"],
    "diff_api_artifacts": ["API-07"],
    "analyze_api_artifact_impact": ["API-08"],
    "archive_api_artifact": ["API-09"],
    "project_audit": ["AUD-01", "MEM-09"],
    "search_project": ["SRCH-01"],
    "read_project_settings": ["PSET-01", "PSET-02", "PSET-03", "PSET-04", "PSET-05", "PSET-06", "PSET-07", "PSET-08", "PSET-09", "PSET-10", "PSET-11", "PSET-12"],
    "update_project_settings": ["PSET-01", "PSET-02", "PSET-03", "PSET-04", "PSET-05", "PSET-06", "PSET-07", "PSET-08", "PSET-09", "PSET-10", "PSET-11", "PSET-12"],
    "project_activity": ["ACT-01", "RPT-07"],
}


def apply_function_ids(app):
    for route in app.routes:
        endpoint = getattr(route, "endpoint", None)
        function_ids = FUNCTION_IDS.get(getattr(endpoint, "__name__", ""))
        if not function_ids:
            continue
        route.openapi_extra = {
            **(getattr(route, "openapi_extra", None) or {}),
            "x-function-ids": function_ids,
        }
