apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-agentic_ai
  labels:
    app: doclib-agentic_ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-agentic_ai
  template:
    metadata:
      labels:
        app: doclib-agentic_ai
    spec:
      containers:
      - name: agentic_ai
        image: doclib_agentic_ai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-agentic_ai
spec:
  selector:
    app: doclib-agentic_ai
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
