apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-authentication
  labels:
    app: doclib-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-authentication
  template:
    metadata:
      labels:
        app: doclib-authentication
    spec:
      containers:
      - name: authentication
        image: doclib_authentication:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-authentication
spec:
  selector:
    app: doclib-authentication
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
