apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-cloud
  labels:
    app: doclib-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-cloud
  template:
    metadata:
      labels:
        app: doclib-cloud
    spec:
      containers:
      - name: cloud
        image: doclib_cloud:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8012
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-cloud
spec:
  selector:
    app: doclib-cloud
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
