apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-collection
  labels:
    app: doclib-collection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-collection
  template:
    metadata:
      labels:
        app: doclib-collection
    spec:
      containers:
      - name: collection
        image: doclib_collection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8005
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-collection
spec:
  selector:
    app: doclib-collection
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
