apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-compilation
  labels:
    app: doclib-compilation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-compilation
  template:
    metadata:
      labels:
        app: doclib-compilation
    spec:
      containers:
      - name: compilation
        image: doclib_compilation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8011
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-compilation
spec:
  selector:
    app: doclib-compilation
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 8011
