apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-drm
  labels:
    app: doclib-drm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-drm
  template:
    metadata:
      labels:
        app: doclib-drm
    spec:
      containers:
      - name: drm
        image: doclib_drm:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8013
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-drm
spec:
  selector:
    app: doclib-drm
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
