apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-finance
  labels:
    app: doclib-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-finance
  template:
    metadata:
      labels:
        app: doclib-finance
    spec:
      containers:
      - name: finance
        image: doclib_finance:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8006
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-finance
spec:
  selector:
    app: doclib-finance
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
