apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-humanity
  labels:
    app: doclib-humanity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-humanity
  template:
    metadata:
      labels:
        app: doclib-humanity
    spec:
      containers:
      - name: humanity
        image: doclib_humanity:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-humanity
spec:
  selector:
    app: doclib-humanity
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
