apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-management
  labels:
    app: doclib-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-management
  template:
    metadata:
      labels:
        app: doclib-management
    spec:
      containers:
      - name: management
        image: doclib_management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-management
spec:
  selector:
    app: doclib-management
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
