apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-messaging
  labels:
    app: doclib-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-messaging
  template:
    metadata:
      labels:
        app: doclib-messaging
    spec:
      containers:
      - name: messaging
        image: doclib_messaging:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8009
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-messaging
spec:
  selector:
    app: doclib-messaging
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 8009
