apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-rag
  labels:
    app: doclib-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-rag
  template:
    metadata:
      labels:
        app: doclib-rag
    spec:
      containers:
      - name: rag
        image: doclib_rag:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-rag
spec:
  selector:
    app: doclib-rag
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
