apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-usage
  labels:
    app: doclib-usage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-usage
  template:
    metadata:
      labels:
        app: doclib-usage
    spec:
      containers:
      - name: usage
        image: doclib_usage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8014
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-usage
spec:
  selector:
    app: doclib-usage
  ports:
    - protocol: TCP
      port: 8014
      targetPort: 8014
