apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclib-websocket
  labels:
    app: doclib-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclib-websocket
  template:
    metadata:
      labels:
        app: doclib-websocket
    spec:
      containers:
      - name: websocket
        image: doclib_websocket:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8010
        envFrom:
        - configMapRef:
            name: doclib-config
---
apiVersion: v1
kind: Service
metadata:
  name: doclib-websocket
spec:
  selector:
    app: doclib-websocket
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
