const fs = require('fs');
const files = fs.readdirSync('.').filter(f => f.startsWith('DocLib') && f.endsWith('.ts'));

const dict = {
  'Xóa nháp': 'Delete draft',
  'Nhập chú thích video...': 'Enter video caption',
  'Nhập link YouTube (VD: https://youtube.com/watch?v=...)': 'Enter YouTube link',
  'Nhúng': 'Embed',
  'Link không hợp lệ! Vui lòng nhập link YouTube.': 'Invalid link! Please enter a YouTube link.',
  'Nhập tên tệp đính kèm...': 'Enter attachment name',
  'Nhập URL file đính kèm...': 'Enter attachment URL',
  'Đính kèm': 'Attach',
  'Nhập nội dung mặt trước...': 'Enter front content',
  'Nhập nội dung mặt sau...': 'Enter back content',
  'Nhập nội dung chú thích (Footnote):': 'Enter footnote content:',
  'Thêm đường dẫn ảnh (URL) vào Thư viện...': 'Add image URL to gallery',
  'Thêm Ảnh': 'Add Image',
  'Nhập chú thích ảnh GIF...': 'Enter GIF caption',
  'Đổi GIF': 'Change GIF',
  'Dán link Giphy (.gif) vào đây...': 'Paste Giphy link here',
  'Chèn GIF': 'Insert GIF',
  'Sửa Link Gist': 'Edit Gist Link',
  'Tên file (tùy chọn)': 'File name (optional)',
  'Nhúng Gist': 'Embed Gist',
  'Link Gist không hợp lệ!': 'Invalid Gist link!',
  'Nhập URL ảnh:': 'Enter image URL:',
  'Nhập URL (nhấn Enter để lưu)...': 'Enter URL (press Enter to save)',
  'Nhập độ cao (px):': 'Enter height (px):',
  'Đổi Link': 'Change Link',
  'Dán Link nhúng (CodePen, CodeSandbox, Figma, Typeform, v.v...)': 'Paste embed link (CodePen, CodeSandbox, Figma, Typeform, etc)',
  'Nhúng (Embed)': 'Embed',
  'Nhập chú thích ảnh...': 'Enter image caption',
  'Dán URL Ảnh trực tiếp:': 'Paste direct Image URL:',
  'Phóng To (Zoom)': 'Zoom',
  'Căn Ngang (X)': 'Horizontal Align (X)',
  'Căn Dọc (Y)': 'Vertical Align (Y)',
  'Dán URL Ảnh để tiến hành Crop/Zoom...': 'Paste Image URL to Crop/Zoom',
  'Tiếp tục': 'Continue',
  'Nhập chú thích Banner...': 'Enter Banner caption',
  'Sửa Link / Đổi Ảnh': 'Edit Link / Change Image',
  'Dán URL Ảnh tĩnh hoặc GIF...': 'Paste Static Image or GIF URL',
  'Dán URL Liên kết đích (khi click vào ảnh)...': 'Paste Destination Link URL (on click)',
  'Tạo Banner': 'Create Banner',
  'Cần làm': 'To Do',
  'Nhiệm vụ 1': 'Task 1',
  'Đang làm': 'In Progress',
  'Hoàn thành': 'Done',
  'Nhập tên công việc...': 'Enter task name',
  'Nhập mã màu (Hex/Tên màu) cho cột này:': 'Enter color code (Hex/Name) for this column:',
  '+ Thêm Card': '+ Add Card',
  'Cột mới': 'New Column',
  'Nhập mã LaTeX ở đây (sẽ được Tectonic biên dịch)...': 'Enter LaTeX code here',
  'bình thường': 'normal',
  'Nhập tiêu đề trang...': 'Enter page title',
  'Nhập mô tả trang...': 'Enter page description',
  'Tên Website...': 'Website Name',
  'Đổi ảnh': 'Change image',
  'Nhập URL ảnh cover cho thẻ link này:': 'Enter cover image URL for this link card:',
  'Dán link (URL) để tạo Bookmark...': 'Paste URL to create Bookmark',
  'Tạo': 'Create',
  'Tìm kiếm tài liệu hoặc dán Link...': 'Search document or paste Link',
  'Tài liệu Hướng dẫn sử dụng': 'User Manual Document',
  'Báo cáo Doanh thu Q3': 'Q3 Revenue Report',
  'Chính sách bảo mật': 'Privacy Policy',
  'Nhập công thức LaTeX...': 'Enter LaTeX formula',
  'Nhập mã Mermaid Graph...': 'Enter Mermaid Graph code',
  'Lỗi cú pháp Mermaid': 'Mermaid Syntax Error',
  'Nhập việc cần làm (Tab/Shift+Tab để thụt lề)...': 'Enter task (Tab/Shift+Tab to indent)',
  'Nhập danh sách...': 'Enter list',
  'Nhập tiêu đề chú ý...': 'Enter notice title',
  'Tên nhân vật...': 'Character name',
  'Mô tả ngắn gọn...': 'Short description',
  'Liên kết (tùy chọn)...': 'Link (optional)',
  'Nhập URL ảnh đại diện:': 'Enter avatar URL:',
  'Lựa chọn 1': 'Option 1',
  'Lựa chọn 2': 'Option 2',
  'Nhập câu hỏi khảo sát...': 'Enter survey question',
  'Nhập lựa chọn...': 'Enter option',
  '+ Thêm Lựa chọn': '+ Add Option',
  'Cơ bản': 'Basic',
  '0đ / tháng': '$0 / month',
  'Tính năng 1': 'Feature 1',
  'Tính năng 2': 'Feature 2',
  '99k / tháng': '$9 / month',
  'Tất cả cơ bản': 'All basic features',
  'Tính năng VIP': 'VIP Feature',
  'Phổ biến nhất': 'Most Popular',
  'Tính năng mới': 'New feature',
  '+ Thêm tính năng': '+ Add feature',
  'Đăng ký ngay': 'Subscribe now',
  'Làm nổi bật': 'Highlight',
  'Xóa gói này': 'Delete this plan',
  'Thêm Gói mới': 'Add New Plan',
  'Gói mới': 'New Plan',
  '0đ': '$0',
  'Tiến độ dự án': 'Project Progress',
  'Nhập câu hỏi trắc nghiệm...': 'Enter quiz question',
  'Nhập đáp án...': 'Enter answer',
  '+ Thêm đáp án': '+ Add answer',
  'Nhập mã HTML tại đây...': 'Enter HTML code here',
  'Nhập đường dẫn ảnh (URL)...': 'Enter image URL',
  'Chèn': 'Insert',
  'Bước 1': 'Step 1',
  'Mô tả chi tiết bước 1': 'Detailed step description 1',
  'Nhập tiêu đề bước...': 'Enter step title',
  'Nhập mô tả chi tiết...': 'Enter detailed description',
  '+ Thêm Bước': '+ Add Step',
  'Đổ bóng (Shadow)': 'Shadow',
  'Bo góc (px)': 'Corner radius (px)',
  '+ Thêm hàng': '+ Add row',
  '+ Thêm cột': '+ Add column',
  '- Bớt hàng': '- Remove row',
  '- Bớt cột': '- Remove column',
  'Nhập link Telegram Post (VD: https://t.me/durov/123)...': 'Enter Telegram Post link',
  'Link không hợp lệ!': 'Invalid link!',
  'Tên Khách Hàng': 'Customer Name',
  'Tên Công Ty': 'Company Name',
  'Ngày Hiện Tại': 'Current Date',
  'Tổng Tiền': 'Total Amount',
  'Nhập nội dung đánh giá của khách hàng...': 'Enter customer review content',
  'Tên khách hàng...': 'Customer name',
  'Chức vụ/Công ty...': 'Position/Company',
  'Nhập URL Avatar khách hàng:': 'Enter customer Avatar URL:',
  'Bắt đầu dự án': 'Start Project',
  'Tháng 1, 2024': 'Jan 2024',
  'Khởi động và lập kế hoạch chi tiết.': 'Kickoff and detailed planning.',
  'Nhập tên sự kiện...': 'Enter event name',
  'Thời gian...': 'Time',
  'Mô tả chi tiết...': 'Detailed description',
  '+ Thêm Mốc Thời Gian': '+ Add Timeline Milestone',
  'Nhập Tiêu Đề Chính...': 'Enter Main Title',
  'Nhập tiêu đề ẩn...': 'Enter hidden title',
  'Nhập nội dung bên trong...': 'Enter inner content',
  'Hoàn tác (Cmd+Z)': 'Undo (Cmd+Z)',
  'Làm lại (Cmd+Shift+Z)': 'Redo (Cmd+Shift+Z)',
  'Nhập link file Video (VD: .mp4, .webm)...': 'Enter Video file link (.mp4, .webm)',
  'Gõ \\"': 'Type \\"',
  '\\" để chọn lệnh...': '\\" for commands'
};

const emojiRegex = /[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F700}-\u{1F77F}\u{1F780}-\u{1F7FF}\u{1F800}-\u{1F8FF}\u{1F900}-\u{1F9FF}\u{1FA00}-\u{1FA6F}\u{1FA70}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu;

for (const file of files) {
  let content = fs.readFileSync(file, 'utf8');
  
  for (const [vi, en] of Object.entries(dict)) {
    content = content.split(vi).join(en);
  }
  
  // Clean all `...`
  content = content.replace(/(['"`])([^'"`]*)\.\.\.([^'"`]*)(['"`])/g, '$1$2$3$4');
  
  // Strip emojis
  content = content.replace(emojiRegex, '');
  
  // Strip // comments except https?://
  content = content.replace(/(?<!https?:)\/\/.*$/gm, '');
  
  fs.writeFileSync(file, content, 'utf8');
}

console.log('Translated successfully!');
