export function emptyDoc() {
  return { type: "doc", content: [] };
}

export function textDoc(text) {
  return {
    type: "doc",
    content: text ? [{ type: "paragraph", content: [{ type: "text", text: String(text) }] }] : [],
  };
}

export function docText(document) {
  const values = [];
  const visit = (node) => {
    if (Array.isArray(node)) return node.forEach(visit);
    if (!node || typeof node !== "object") return;
    if (typeof node.text === "string") values.push(node.text);
    if (node.content) visit(node.content);
  };
  visit(document);
  return values.join(" ").trim();
}

const labels = {
  ACCEPTED: "Đã chấp nhận",
  ACTIVE: "Đang hoạt động",
  APPLY_PARTIAL: "Áp dụng một phần",
  ANALYZED: "Đã phân tích",
  APPROVED: "Đã phê duyệt",
  ARCHIVED: "Đã lưu trữ",
  AUTHENTICATED: "Tài khoản đã xác thực",
  BASELINED: "Đã đặt làm phiên bản chuẩn",
  BLOCKED: "Bị chặn",
  BOUND: "Đã liên kết",
  CHANGED: "Đã thay đổi",
  CLOSED: "Đã đóng",
  COMPLETED: "Đã hoàn tất",
  CONFIRMED: "Đã xác nhận",
  CREATED: "Đã tạo",
  DEGRADED: "Hoạt động giới hạn",
  DEGRADED_AI: "AI hoạt động giới hạn",
  DUPLICATE: "Trùng lặp",
  DRAFT: "Bản nháp",
  DISABLED: "Đã vô hiệu hóa",
  EDITED_ACCEPTED: "Đã chấp nhận sau chỉnh sửa",
  EXPIRED: "Đã hết hạn",
  FAIL: "Thất bại",
  FAILED: "Không thành công",
  FRESH: "Còn hiệu lực",
  HISTORICAL: "Lịch sử",
  IN_REVIEW: "Đang chờ duyệt",
  IN_PROGRESS: "Đang thực hiện",
  INACTIVE: "Đã vô hiệu hóa",
  INVITED: "Đã mời",
  LOCKED: "Đã khóa",
  MUST_RUN: "Bắt buộc chạy",
  NEEDS_UPDATE: "Cần cập nhật",
  NEW: "Mới",
  NORMAL: "Bình thường",
  NOT_APPLICABLE: "Không áp dụng",
  NOT_RUN: "Chưa chạy",
  OBSOLETE: "Không còn phù hợp",
  OPEN: "Đang mở",
  OPTIONAL: "Không bắt buộc",
  PASS: "Đạt",
  PARTIAL_EXECUTION: "Thực thi một phần",
  PARSE_FAILED: "Phân tích tệp thất bại",
  PENDING: "Chờ duyệt",
  PENDING_APPROVAL: "Chờ phê duyệt",
  POTENTIALLY_AFFECTED: "Có thể bị ảnh hưởng",
  PREVIEW_READY: "Sẵn sàng xem trước",
  QUEUED: "Đang chờ xử lý",
  READY: "Sẵn sàng",
  READY_FOR_RETEST: "Sẵn sàng kiểm thử lại",
  REJECTED: "Đã từ chối",
  REVIEWED: "Đã rà soát",
  REVIEW_READY: "Sẵn sàng rà soát",
  REOPENED: "Đã mở lại",
  RESOLVED: "Đã xử lý",
  SHOULD_RUN: "Nên chạy",
  SKIPPED: "Đã bỏ qua",
  STALE: "Đã lỗi thời",
  STILL_VALID: "Vẫn hợp lệ",
  SUCCESS: "Thành công",
  SUGGESTED: "AI đề xuất",
  SUPERSEDED: "Đã được thay thế",
  SUSPENDED: "Tạm ngưng",
  UNCHANGED: "Không thay đổi",
  UNKNOWN: "Chưa xác định",
  INDEXED: "Đã lập chỉ mục",
  INDEXING: "Đang lập chỉ mục",
  ABORTED: "Đã hủy",
  CANCELLED: "Đã hủy",
  EXTRACTED: "Đã trích xuất",
};

const valueLabels = {
  ADMIN: "Quản trị viên",
  USER: "Người dùng",
  QA_LEAD: "Trưởng nhóm kiểm thử",
  TESTER: "Kiểm thử viên",
  BA: "Chuyên viên phân tích nghiệp vụ",
  DEVELOPER: "Lập trình viên",
  VIEWER: "Người xem",
  ADMIN_ONLY: "Chỉ quản trị viên",
  ALL_SERVICE_IDENTITIES: "Mọi danh tính dịch vụ",
  ALL_USERS: "Mọi tài khoản",
  APPLY_INCOMING: "Áp dụng dữ liệu nhận về",
  AUTHENTICATED: "Tài khoản đã xác thực",
  BIDIRECTIONAL: "Hai chiều",
  BREAK_GLASS: "Truy cập khẩn cấp",
  KEEP_CURRENT: "Giữ dữ liệu hiện tại",
  KEEP_LOCAL: "Giữ dữ liệu nội bộ",
  KEEP_REMOTE: "Giữ dữ liệu bên ngoài",
  PROJECT_METADATA: "Siêu dữ liệu dự án",
  PULL: "Nhận dữ liệu",
  PUSH: "Gửi dữ liệu",
  RATE_LIMITS: "Giới hạn truy cập",
  SAFE_ALL: "Mọi thao tác an toàn",
  SERVICE_IDENTITY: "Danh tính dịch vụ",
  DEFECT_CREATED: "Lỗi được tạo",
  Project: "Dự án",
  ProjectSettings: "Cài đặt dự án",
  TestSuite: "Bộ kiểm thử",
  TestPlan: "Kế hoạch kiểm thử",
  RequirementDocument: "Tài liệu yêu cầu",
  Requirement: "Yêu cầu",
  project_permission_denied: "Từ chối quyền dự án",
  project_settings_updated: "Cập nhật cài đặt dự án",
  test_suite_created: "Tạo bộ kiểm thử",
  test_plan_created: "Tạo kế hoạch kiểm thử",
  requirement_document_reindexed: "Lập chỉ mục lại tài liệu yêu cầu",
  knowledge_source_created: "Tạo nguồn tri thức",
  requirement_created: "Tạo yêu cầu",
  requirement_document_created: "Tạo tài liệu yêu cầu",
  requirement_extraction_requested: "Yêu cầu trích xuất nội dung yêu cầu",
  requirement_extraction_completed: "Hoàn tất trích xuất nội dung yêu cầu",
  project_created: "Tạo dự án",
  ADMIN_USER_MEMBERSHIPS_VIEWED: "Xem vai trò dự án của tài khoản",
  ADMIN_USER_SESSIONS_VIEWED: "Xem phiên đăng nhập của tài khoản",
  REGISTER_USER: "Đăng ký tài khoản",
  EMAIL_VERIFICATION_REQUESTED: "Yêu cầu xác minh email",
  review_comment_created: "Tạo nhận xét rà soát",
  regression_recommendation_created: "Tạo đề xuất hồi quy",
  maintenance_proposal_applied: "Áp dụng đề xuất bảo trì",
  maintenance_proposals_created: "Tạo đề xuất bảo trì",
  impact_analysis_reviewed: "Rà soát phân tích ảnh hưởng",
  ReviewComment: "Nhận xét rà soát",
  RegressionRecommendation: "Đề xuất hồi quy",
  MaintenanceProposal: "Đề xuất bảo trì",
  ImpactAnalysis: "Phân tích ảnh hưởng",
  authentication: "Xác thực",
  testing: "Kiểm thử",
  worker: "Xử lý nền",
  ai: "Trí tuệ nhân tạo",
  content: "Nội dung",
  mongodb: "Cơ sở dữ liệu",
  web: "Ứng dụng web",
  chat: "Trò chuyện",
  reference: "Tài liệu tham chiếu",
  teacher_material: "Tài liệu giáo viên",
  official_textbook: "Sách giáo khoa chính thức",
  curriculum: "Chương trình học",
  other: "Nguồn khác",
  teacher: "Giáo viên",
  official: "Chính thức",
  supplemental: "Bổ trợ",
  "duplicate.scan.requested": "Yêu cầu kiểm tra trùng lặp",
  UPDATE_TEST_CASE: "Cập nhật ca kiểm thử",
  CREATE_TEST_CASE: "Tạo ca kiểm thử",
  OBSOLETE_TEST_CASE: "Đánh dấu ca kiểm thử không còn phù hợp",
  TEXT_ONLY: "Chỉ thay đổi cách diễn đạt",
  MODIFIED_INPUT: "Thay đổi dữ liệu đầu vào",
  MODIFIED_BOUNDARY: "Thay đổi giá trị biên",
  MODIFIED_PERMISSION: "Thay đổi phân quyền",
  MODIFIED_ERROR: "Thay đổi xử lý lỗi",
  ADDED_BEHAVIOR: "Thêm hành vi",
  REMOVED_BEHAVIOR: "Loại bỏ hành vi",
  requirement_documents: "Tài liệu yêu cầu",
  test_case_versions: "Phiên bản ca kiểm thử",
  api: "API",
  blocker: "Chặn toàn bộ",
  boundary: "Giá trị biên",
  business_rule: "Quy tắc nghiệp vụ",
  concurrency: "Xử lý đồng thời",
  critical: "Nghiêm trọng",
  custom: "Tùy chỉnh",
  data_persistence: "Lưu trữ dữ liệu",
  error_handling: "Xử lý lỗi",
  feature: "Theo tính năng",
  functional: "Chức năng",
  happy_path: "Luồng thành công",
  high: "Cao",
  integration: "Tích hợp",
  low: "Thấp",
  major: "Lớn",
  medium: "Trung bình",
  minor: "Nhỏ",
  negative: "Tình huống lỗi",
  non_functional: "Phi chức năng",
  permission: "Phân quyền",
  regression: "Hồi quy",
  smoke: "Kiểm tra nhanh",
  state_transition: "Chuyển trạng thái",
  trivial: "Không đáng kể",
  ui: "Giao diện",
  validation: "Xác thực dữ liệu",
};

export function statusLabel(value) {
  return labels[value] || String(value || "Chưa xác định");
}

export function valueLabel(value) {
  return valueLabels[value] || statusLabel(value);
}

export function formatDate(value) {
  return value ? new Date(value).toLocaleString("vi-VN") : "Chưa có";
}

export function messageOf(reason) {
  return reason instanceof Error ? reason.message : "Không thể hoàn tất thao tác";
}
