import os
from typing import Optional

from pydantic import BaseModel

class Settings(BaseModel):
    PROJECT_NAME: str = os.getenv("PROJECT_NAME")
    VERSION: str = os.getenv("VERSION")
    SECRET_KEY: str = os.getenv("SECRET_KEY")
    CORS_ALLOWED_ORIGINS: str = os.getenv("CORS_ALLOWED_ORIGINS")
    ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
    REFRESH_TOKEN_EXPIRE_DAYS: int = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS"))
    PLATFORM_SYSTEM_ID: str = os.getenv("PLATFORM_SYSTEM_ID")
    MONGODB_URI: str = os.getenv("MONGODB_URI")
    MONGODB_DB_NAME: str = os.getenv("MONGODB_DB_NAME")
    SERVICE_DB_NAME: str = os.getenv("SERVICE_DB_NAME", os.getenv("MONGODB_DB_NAME"))
    REDIS_URI: str = os.getenv("REDIS_URI")
    GOOGLE_CLIENT_ID: Optional[str] = os.getenv("GOOGLE_CLIENT_ID")
    GOOGLE_CLIENT_SECRET: Optional[str] = os.getenv("GOOGLE_CLIENT_SECRET")
    GOOGLE_REDIRECT_URI: Optional[str] = os.getenv("GOOGLE_REDIRECT_URI")
    GOOGLE_AUTH_URL: str = os.getenv("GOOGLE_AUTH_URL")
    GOOGLE_TOKEN_URL: str = os.getenv("GOOGLE_TOKEN_URL")
    GOOGLE_USERINFO_URL: str = os.getenv("GOOGLE_USERINFO_URL")
    PASSKEY_RP_ID: str = os.getenv("PASSKEY_RP_ID")
    PASSKEY_RP_NAME: str = os.getenv("PASSKEY_RP_NAME")
    PASSKEY_ALLOWED_ORIGINS: str = os.getenv("PASSKEY_ALLOWED_ORIGINS")
    SMTP_HOST: str = os.getenv("SMTP_HOST")
    SMTP_PORT: int = int(os.getenv("SMTP_PORT"))
    SMTP_USER: Optional[str] = os.getenv("SMTP_USER")
    SMTP_PASS: Optional[str] = os.getenv("SMTP_PASS")
    SENDER_EMAIL: Optional[str] = os.getenv("SENDER_EMAIL")
    SENDER_NAME: Optional[str] = os.getenv("SENDER_NAME")
    API_URL: str = os.getenv("API_URL")
    AGENTIC_AI_URL: str = os.getenv("AGENTIC_AI_URL")
    SHARED_URL: Optional[str] = os.getenv("SHARED_URL")
    COMPILATION_URL: str = os.getenv("COMPILATION_URL")
    COLLECTION_URL: str = os.getenv("COLLECTION_URL")
    MESSAGING_URL: str = os.getenv("MESSAGING_URL")
    PAYMENT_URL: str = os.getenv("PAYMENT_URL")
    NOTIFICATION_URL: str = os.getenv("NOTIFICATION_URL")
    MANAGEMENT_URL: str = os.getenv("MANAGEMENT_URL")
    AUTHENTICATION_URL: str = os.getenv("AUTHENTICATION_URL")
    CONTENT_URL: str = os.getenv("CONTENT_URL")
    WEBSOCKET_URL: str = os.getenv("WEBSOCKET_URL")
    FLARESOLVERR_URL: str = os.getenv("FLARESOLVERR_URL")
    DEFAULT_PAGE_LIMIT: int = int(os.getenv("DEFAULT_PAGE_LIMIT"))
    MAX_PAGE_LIMIT: int = int(os.getenv("MAX_PAGE_LIMIT"))
    DEFAULT_HTTP_TIMEOUT: float = float(os.getenv("DEFAULT_HTTP_TIMEOUT"))
    LONG_PROCESS_TIMEOUT: float = float(os.getenv("LONG_PROCESS_TIMEOUT"))

settings = Settings()
