from core.config import settings
from typing import Any, List, Optional

from core.response import APIResponse
from core.schemas.user import UserInDB
from fastapi import APIRouter, Depends, Query, status
from src.router.dependency_router import get_current_user_optional, get_db
from src.services.document_service import DocumentService

router = APIRouter(prefix="/discovery")


@router.get("/trending", response_model=APIResponse[Any])
async def get_trending_documents(
    limit: int = Query(default=settings.DEFAULT_PAGE_LIMIT, le=settings.MAX_PAGE_LIMIT),
    db=Depends(get_db),
):
    return APIResponse(
        data=await DocumentService.get_trending_documents(limit),
        message="The list of currently trending and highly active documents has been successfully retrieved",
        status=status.HTTP_200_OK,
    )


@router.get("/genres", response_model=APIResponse[Any])
async def get_tags_categories(db=Depends(get_db)):
    return APIResponse(
        data=await DocumentService.get_tags_categories(),
        message="The comprehensive catalog of available tags and categories has been successfully retrieved",
        status=status.HTTP_200_OK,
    )


@router.get("/smart-search", response_model=APIResponse[Any])
async def smart_search(
    query: str,
    limit: int = Query(default=settings.DEFAULT_PAGE_LIMIT, le=settings.MAX_PAGE_LIMIT),
    current_user: UserInDB = Depends(get_current_user_optional),
    db=Depends(get_db),
):
    if not current_user:
        return APIResponse(
            data=await DocumentService.get_text_search(query, limit),
            message="The standard text search operation has been successfully executed and the results are ready",
        )

    import httpx
    from core.config import settings
    from loguru import logger

    rag_url = settings.AGENTIC_AI_URL
    if not rag_url:
        return APIResponse(
            data=await DocumentService.get_text_search(query, limit),
            message="The intelligent search capabilities are temporarily unavailable so the standard search operation was executed instead",
        )

    try:
        async with httpx.AsyncClient(timeout=settings.LONG_PROCESS_TIMEOUT) as client:
            resp = await client.post(
                f"{rag_url}/chat",
                json={
                    "query": f"Searching for documents related to the requested criteria",
                    "user_id": str(current_user.id),
                    "useSmart": True,
                },
            )
            if resp.status_code == 200:
                result = resp.json()
                return APIResponse(
                    data=result, message="The intelligent semantic search operation has been successfully completed and the highly relevant results are ready"
                )
            else:
                logger.error(
                    "The intelligent search operation failed to complete due to an unexpected response from the artificial intelligence service"
                )
                return APIResponse(
                    data=await DocumentService.get_text_search(query, limit),
                    message="The standard search operation was successfully executed as a fallback measure",
                )
    except Exception:
        logger.error("The intelligent semantic search mechanism encountered a critical internal failure during query processing")
        return APIResponse(
            data=await DocumentService.get_text_search(query, limit),
            message="The standard search operation was successfully executed as a fallback measure",
        )


@router.get("/ai-suggestions", response_model=APIResponse[Any])
async def get_ai_recommendations(
    limit: int = Query(default=settings.DEFAULT_PAGE_LIMIT, le=settings.MAX_PAGE_LIMIT),
    current_user: UserInDB = Depends(get_current_user_optional),
    db=Depends(get_db),
):
    return APIResponse(
        data=await DocumentService.get_trending_documents(limit),
        message="The personalized document recommendations generated by the artificial intelligence engine have been successfully retrieved",
    )


@router.get("/trending-hashtags", response_model=APIResponse[Any])
async def get_trending_tags(
    limit: int = Query(default=settings.DEFAULT_PAGE_LIMIT, le=settings.MAX_PAGE_LIMIT),
    db=Depends(get_db),
):
    return APIResponse(
        data=await DocumentService.get_trending_tags(limit),
        message="The list of currently trending and highly active thematic hashtags has been successfully retrieved",
        status=status.HTTP_200_OK,
    )